# Change these first
owner: jc-hiroto # Your GitHub organization or username, where this repository lives
repo: portfolio-upptime # The name of this repository

sites:
  - name: Portfolio Website
    url: https://jchiroto.dev
    
status-website:
  cname: status.jchiroto.dev
  logoUrl: https://raw.githubusercontent.com/jc-hiroto/me/master/public/apple-touch-icon.png
  name: James (jc-hiroto)
  introTitle: This site monitors some interesting websites created by me!
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
